CREATE TABLE KUCANSTVO(
	id INTEGER PRIMARY KEY,
	ulica VARCHAR(100) NOT NULL,
	kucni_broj INTEGER NOT NULL,
	grad VARCHAR(100) NOT NULL,
	drzava VARCHAR(100)
);

CREATE TABLE FAKULTET(
	id INTEGER PRIMARY KEY,
	naziv VARCHAR(500) NOT NULL,
	adresa VARCHAR(500) NOT NULL,
	grad VARCHAR(500) NOT NULL,
	drzava VARCHAR(100)
);

CREATE TABLE STUDENT(
	id INTEGER PRIMARY KEY,
    ime VARCHAR(100) NOT NULL,
	prezime VARCHAR(100) NOT NULL,
	datum_rodjenja DATE NOT NULL,
	kucanstvo_id INTEGER REFERENCES KUCANSTVO(id),
	fakultet_id INTEGER REFERENCES FAKULTET(id)
);

CREATE TABLE INDEKS(
	id INTEGER REFERENCES STUDENT(id) PRIMARY KEY,
	broj_indeksa INTEGER
);

CREATE TABLE KOLEGIJ (
	id INTEGER PRIMARY KEY,
	naziv VARCHAR(100) NOT NULL UNIQUE,
	broj_ECTS INTEGER NOT NULL,
	fakultet_id INTEGER REFERENCES FAKULTET(id)
);

CREATE TABLE KOLEGIJ_STUDENT (
	kolegij_id INTEGER REFERENCES KOLEGIJ(id),
    student_id INTEGER REFERENCES STUDENT(id),
    CONSTRAINT id PRIMARY KEY (kolegij_id, student_id),
);

